# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameInfo_TabWidget.ui'
#
# Created: Mon Sep 15 14:33:58 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InfoTabWidget(object):
    def setupUi(self, InfoTabWidget):
        InfoTabWidget.setObjectName(_fromUtf8("InfoTabWidget"))
        InfoTabWidget.resize(242, 381)
        self.ActionTab = QtGui.QWidget()
        self.ActionTab.setObjectName(_fromUtf8("ActionTab"))
        self.layoutWidget = QtGui.QWidget(self.ActionTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 213, 178))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        InfoTabWidget.addTab(self.ActionTab, _fromUtf8(""))
        self.UnitTab = QtGui.QWidget()
        self.UnitTab.setObjectName(_fromUtf8("UnitTab"))
        self.layoutWidget1 = QtGui.QWidget(self.UnitTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 211, 334))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_2.addWidget(self.lineEdit_8, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_2.addWidget(self.lineEdit_11, 5, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_2.addWidget(self.lineEdit_12, 6, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_2.addWidget(self.lineEdit_9, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_2.addWidget(self.lineEdit_10, 4, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_2.addWidget(self.lineEdit_14, 8, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 9, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 8, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 10, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 11, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_2.addWidget(self.lineEdit_18, 12, 2, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_2.addWidget(self.lineEdit_15, 9, 2, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_2.addWidget(self.lineEdit_13, 7, 2, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_2.addWidget(self.lineEdit_17, 11, 2, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_2.addWidget(self.lineEdit_16, 10, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget1)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 12, 0, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_2.addWidget(self.lineEdit_19, 3, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 13, 0, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_2.addWidget(self.lineEdit_20, 13, 2, 1, 1)
        InfoTabWidget.addTab(self.UnitTab, _fromUtf8(""))
        self.MapTab = QtGui.QWidget()
        self.MapTab.setObjectName(_fromUtf8("MapTab"))
        self.layoutWidget2 = QtGui.QWidget(self.MapTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 211, 92))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_22 = QtGui.QLabel(self.layoutWidget2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_3.addWidget(self.lineEdit_21, 0, 1, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_3.addWidget(self.lineEdit_22, 1, 1, 1, 1)
        self.lineEdit_23 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.gridLayout_3.addWidget(self.lineEdit_23, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        InfoTabWidget.addTab(self.MapTab, _fromUtf8(""))
        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_2)
        self.label_8.setBuddy(self.lineEdit_3)
        self.label_7.setBuddy(self.lineEdit_4)
        self.label_3.setBuddy(self.lineEdit_5)
        self.label_4.setBuddy(self.lineEdit_6)
        self.label_5.setBuddy(self.lineEdit_7)
        self.label_9.setBuddy(self.lineEdit_19)
        self.label_11.setBuddy(self.lineEdit_12)
        self.label_12.setBuddy(self.lineEdit_9)
        self.label_6.setBuddy(self.lineEdit_8)
        self.label_10.setBuddy(self.lineEdit_10)
        self.label_13.setBuddy(self.lineEdit_11)
        self.label_14.setBuddy(self.lineEdit_13)
        self.label_17.setBuddy(self.lineEdit_15)
        self.label_15.setBuddy(self.lineEdit_14)
        self.label_16.setBuddy(self.lineEdit_16)
        self.label_18.setBuddy(self.lineEdit_17)
        self.label_19.setBuddy(self.lineEdit_18)
        self.label_23.setBuddy(self.lineEdit_20)
        self.label_22.setBuddy(self.lineEdit_23)
        self.label_21.setBuddy(self.lineEdit_22)
        self.label_20.setBuddy(self.lineEdit_21)

        self.retranslateUi(InfoTabWidget)
        InfoTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(InfoTabWidget)

    def retranslateUi(self, InfoTabWidget):
        InfoTabWidget.setWindowTitle(_translate("InfoTabWidget", "信息栏", None))
        self.label.setText(_translate("InfoTabWidget", "回合数：", None))
        self.label_2.setText(_translate("InfoTabWidget", "回合用时：", None))
        self.label_8.setText(_translate("InfoTabWidget", "资源数：", None))
        self.label_7.setText(_translate("InfoTabWidget", "基地生命：", None))
        self.label_3.setText(_translate("InfoTabWidget", "空中单位数：", None))
        self.label_4.setText(_translate("InfoTabWidget", "水面单位数：", None))
        self.label_5.setText(_translate("InfoTabWidget", "水下单位数：", None))
        InfoTabWidget.setTabText(InfoTabWidget.indexOf(self.ActionTab), _translate("InfoTabWidget", "游戏信息", None))
        self.label_9.setText(_translate("InfoTabWidget", "攻击力：", None))
        self.label_11.setText(_translate("InfoTabWidget", "速度：", None))
        self.label_12.setText(_translate("InfoTabWidget", "机群构成：  ", None))
        self.label_6.setText(_translate("InfoTabWidget", "种类：", None))
        self.label_10.setText(_translate("InfoTabWidget", "防御力：", None))
        self.label_13.setText(_translate("InfoTabWidget", "血量：", None))
        self.label_14.setText(_translate("InfoTabWidget", "燃料：", None))
        self.label_17.setText(_translate("InfoTabWidget", "视野：", None))
        self.label_15.setText(_translate("InfoTabWidget", "弹药：", None))
        self.label_16.setText(_translate("InfoTabWidget", "携带资源：", None))
        self.label_18.setText(_translate("InfoTabWidget", "移动目标：", None))
        self.label_19.setText(_translate("InfoTabWidget", "攻击目标：", None))
        self.label_23.setText(_translate("InfoTabWidget", "指令：", None))
        InfoTabWidget.setTabText(InfoTabWidget.indexOf(self.UnitTab), _translate("InfoTabWidget", "单位信息", None))
        self.label_22.setText(_translate("InfoTabWidget", "工作：", None))
        self.label_21.setText(_translate("InfoTabWidget", "资源：    ", None))
        self.label_20.setText(_translate("InfoTabWidget", "地形：      ", None))
        InfoTabWidget.setTabText(InfoTabWidget.indexOf(self.MapTab), _translate("InfoTabWidget", "地图信息", None))

