# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameInfo2.ui'
#
# Created: Mon Sep 15 17:11:05 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GameInfo2(object):
    def setupUi(self, GameInfo2):
        GameInfo2.setObjectName(_fromUtf8("GameInfo2"))
        GameInfo2.resize(235, 451)
        self.layoutWidget = QtGui.QWidget(GameInfo2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 430))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 16, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 12, 0, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout_2.addWidget(self.lineEdit_19, 3, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 13, 0, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_2.addWidget(self.lineEdit_16, 10, 2, 1, 1)
        self.lineEdit_20 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.gridLayout_2.addWidget(self.lineEdit_20, 13, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 14, 0, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout_2.addWidget(self.lineEdit_22, 16, 2, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout_2.addWidget(self.lineEdit_21, 14, 2, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_2.addWidget(self.lineEdit_8, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_2.addWidget(self.lineEdit_12, 6, 2, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_2.addWidget(self.lineEdit_11, 5, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_2.addWidget(self.lineEdit_9, 2, 2, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_2.addWidget(self.lineEdit_10, 4, 2, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout_2.addWidget(self.lineEdit_14, 8, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 9, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 10, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 11, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 8, 0, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout_2.addWidget(self.lineEdit_18, 12, 2, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout_2.addWidget(self.lineEdit_15, 9, 2, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_2.addWidget(self.lineEdit_13, 7, 2, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout_2.addWidget(self.lineEdit_17, 11, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 15, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 15, 2, 1, 1)
        self.label_21.setBuddy(self.lineEdit_22)
        self.label_6.setBuddy(self.lineEdit_8)
        self.label_19.setBuddy(self.lineEdit_18)
        self.label_23.setBuddy(self.lineEdit_20)
        self.label_20.setBuddy(self.lineEdit_21)
        self.label_9.setBuddy(self.lineEdit_19)
        self.label_11.setBuddy(self.lineEdit_12)
        self.label_12.setBuddy(self.lineEdit_9)
        self.label_10.setBuddy(self.lineEdit_10)
        self.label_17.setBuddy(self.lineEdit_15)
        self.label_13.setBuddy(self.lineEdit_11)
        self.label_14.setBuddy(self.lineEdit_13)
        self.label_16.setBuddy(self.lineEdit_16)
        self.label_18.setBuddy(self.lineEdit_17)
        self.label_15.setBuddy(self.lineEdit_14)

        self.retranslateUi(GameInfo2)
        QtCore.QMetaObject.connectSlotsByName(GameInfo2)

    def retranslateUi(self, GameInfo2):
        GameInfo2.setWindowTitle(_translate("GameInfo2", "单位信息", None))
        self.label_21.setText(_translate("GameInfo2", "资源：    ", None))
        self.label_6.setText(_translate("GameInfo2", "种类：", None))
        self.label_19.setText(_translate("GameInfo2", "攻击目标：", None))
        self.label_23.setText(_translate("GameInfo2", "指令：", None))
        self.label_20.setText(_translate("GameInfo2", "地形：      ", None))
        self.label_9.setText(_translate("GameInfo2", "攻击力：", None))
        self.label_11.setText(_translate("GameInfo2", "速度：", None))
        self.label_12.setText(_translate("GameInfo2", "机群构成：  ", None))
        self.label_10.setText(_translate("GameInfo2", "防御力：", None))
        self.label_17.setText(_translate("GameInfo2", "视野：", None))
        self.label_13.setText(_translate("GameInfo2", "血量：", None))
        self.label_14.setText(_translate("GameInfo2", "燃料：", None))
        self.label_16.setText(_translate("GameInfo2", "携带资源：", None))
        self.label_18.setText(_translate("GameInfo2", "移动目标：", None))
        self.label_15.setText(_translate("GameInfo2", "弹药：", None))
        self.label.setText(_translate("GameInfo2", "坐标：", None))

