# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mapmaker.ui'
#
# Created: Tue Sep 23 21:01:02 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mapmaker(object):
    def setupUi(self, Mapmaker):
        Mapmaker.setObjectName(_fromUtf8("Mapmaker"))
        Mapmaker.resize(1344, 889)
        self.UnitTabWidget = QtGui.QTabWidget(Mapmaker)
        self.UnitTabWidget.setGeometry(QtCore.QRect(1140, 30, 201, 481))
        self.UnitTabWidget.setObjectName(_fromUtf8("UnitTabWidget"))
        self.MapUnitTab = QtGui.QWidget()
        self.MapUnitTab.setObjectName(_fromUtf8("MapUnitTab"))
        self.label = QtGui.QLabel(self.MapUnitTab)
        self.label.setGeometry(QtCore.QRect(10, 390, 54, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.SymmetryComboBox = QtGui.QComboBox(self.MapUnitTab)
        self.SymmetryComboBox.setGeometry(QtCore.QRect(20, 420, 91, 22))
        self.SymmetryComboBox.setObjectName(_fromUtf8("SymmetryComboBox"))
        self.SymmetryComboBox.addItem(_fromUtf8(""))
        self.SymmetryComboBox.addItem(_fromUtf8(""))
        self.SymmetryComboBox.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.MapUnitTab)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.MapUnitTab)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 61, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.layoutWidget = QtGui.QWidget(self.MapUnitTab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 140, 91, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.BaseRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.BaseRadioButton.setObjectName(_fromUtf8("BaseRadioButton"))
        self.verticalLayout.addWidget(self.BaseRadioButton)
        self.MineRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.MineRadioButton.setObjectName(_fromUtf8("MineRadioButton"))
        self.verticalLayout.addWidget(self.MineRadioButton)
        self.OilRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.OilRadioButton.setObjectName(_fromUtf8("OilRadioButton"))
        self.verticalLayout.addWidget(self.OilRadioButton)
        self.SurfaceRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.SurfaceRadioButton.setObjectName(_fromUtf8("SurfaceRadioButton"))
        self.verticalLayout.addWidget(self.SurfaceRadioButton)
        self.IslandRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.IslandRadioButton.setObjectName(_fromUtf8("IslandRadioButton"))
        self.verticalLayout.addWidget(self.IslandRadioButton)
        self.DeleteTerrainRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.DeleteTerrainRadioButton.setObjectName(_fromUtf8("DeleteTerrainRadioButton"))
        self.verticalLayout.addWidget(self.DeleteTerrainRadioButton)
        self.layoutWidget1 = QtGui.QWidget(self.MapUnitTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 115, 52))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.RowLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.RowLineEdit.setObjectName(_fromUtf8("RowLineEdit"))
        self.horizontalLayout.addWidget(self.RowLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.ColumnLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.ColumnLineEdit.setObjectName(_fromUtf8("ColumnLineEdit"))
        self.horizontalLayout_2.addWidget(self.ColumnLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.UnitTabWidget.addTab(self.MapUnitTab, _fromUtf8(""))
        self.SoldierUnitTab = QtGui.QWidget()
        self.SoldierUnitTab.setObjectName(_fromUtf8("SoldierUnitTab"))
        self.label_6 = QtGui.QLabel(self.SoldierUnitTab)
        self.label_6.setGeometry(QtCore.QRect(10, 250, 171, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget2 = QtGui.QWidget(self.SoldierUnitTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 270, 176, 22))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.WarplaneLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.WarplaneLineEdit.setObjectName(_fromUtf8("WarplaneLineEdit"))
        self.horizontalLayout_3.addWidget(self.WarplaneLineEdit)
        self.TorpedoLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.TorpedoLineEdit.setObjectName(_fromUtf8("TorpedoLineEdit"))
        self.horizontalLayout_3.addWidget(self.TorpedoLineEdit)
        self.BomberLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.BomberLineEdit.setObjectName(_fromUtf8("BomberLineEdit"))
        self.horizontalLayout_3.addWidget(self.BomberLineEdit)
        self.ScoutplaneLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.ScoutplaneLineEdit.setObjectName(_fromUtf8("ScoutplaneLineEdit"))
        self.horizontalLayout_3.addWidget(self.ScoutplaneLineEdit)
        self.DeleteUnitRadioButton = QtGui.QRadioButton(self.SoldierUnitTab)
        self.DeleteUnitRadioButton.setGeometry(QtCore.QRect(10, 310, 89, 16))
        self.DeleteUnitRadioButton.setObjectName(_fromUtf8("DeleteUnitRadioButton"))
        self.layoutWidget3 = QtGui.QWidget(self.SoldierUnitTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 158, 241))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.SubmarineRadioButton = QtGui.QRadioButton(self.layoutWidget3)
        self.SubmarineRadioButton.setObjectName(_fromUtf8("SubmarineRadioButton"))
        self.verticalLayout_3.addWidget(self.SubmarineRadioButton)
        self.DestroyerRadioButton = QtGui.QRadioButton(self.layoutWidget3)
        self.DestroyerRadioButton.setObjectName(_fromUtf8("DestroyerRadioButton"))
        self.verticalLayout_3.addWidget(self.DestroyerRadioButton)
        self.CruiserRadioButton = QtGui.QRadioButton(self.layoutWidget3)
        self.CruiserRadioButton.setObjectName(_fromUtf8("CruiserRadioButton"))
        self.verticalLayout_3.addWidget(self.CruiserRadioButton)
        self.BattleshipRadioButton = QtGui.QRadioButton(self.layoutWidget3)
        self.BattleshipRadioButton.setObjectName(_fromUtf8("BattleshipRadioButton"))
        self.verticalLayout_3.addWidget(self.BattleshipRadioButton)
        self.CarrierRadioButton = QtGui.QRadioButton(self.layoutWidget3)
        self.CarrierRadioButton.setObjectName(_fromUtf8("CarrierRadioButton"))
        self.verticalLayout_3.addWidget(self.CarrierRadioButton)
        self.CargoRadioButton = QtGui.QRadioButton(self.layoutWidget3)
        self.CargoRadioButton.setObjectName(_fromUtf8("CargoRadioButton"))
        self.verticalLayout_3.addWidget(self.CargoRadioButton)
        self.FormationRadioButton = QtGui.QRadioButton(self.layoutWidget3)
        self.FormationRadioButton.setObjectName(_fromUtf8("FormationRadioButton"))
        self.verticalLayout_3.addWidget(self.FormationRadioButton)
        self.UnitTabWidget.addTab(self.SoldierUnitTab, _fromUtf8(""))
        self.ExitButton = QtGui.QPushButton(Mapmaker)
        self.ExitButton.setGeometry(QtCore.QRect(10, 10, 31, 23))
        self.ExitButton.setObjectName(_fromUtf8("ExitButton"))
        self.HelpButton = QtGui.QPushButton(Mapmaker)
        self.HelpButton.setGeometry(QtCore.QRect(50, 10, 31, 23))
        self.HelpButton.setObjectName(_fromUtf8("HelpButton"))
        self.NewFileButton = QtGui.QPushButton(Mapmaker)
        self.NewFileButton.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.NewFileButton.setObjectName(_fromUtf8("NewFileButton"))
        self.OpenFileButton = QtGui.QPushButton(Mapmaker)
        self.OpenFileButton.setGeometry(QtCore.QRect(300, 10, 75, 23))
        self.OpenFileButton.setObjectName(_fromUtf8("OpenFileButton"))
        self.SaveButton = QtGui.QPushButton(Mapmaker)
        self.SaveButton.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.SaveButton.setObjectName(_fromUtf8("SaveButton"))
        self.SaveAsButton = QtGui.QPushButton(Mapmaker)
        self.SaveAsButton.setGeometry(QtCore.QRect(480, 10, 75, 23))
        self.SaveAsButton.setObjectName(_fromUtf8("SaveAsButton"))
        self.RandomButton = QtGui.QPushButton(Mapmaker)
        self.RandomButton.setGeometry(QtCore.QRect(570, 10, 75, 23))
        self.RandomButton.setObjectName(_fromUtf8("RandomButton"))
        self.formLayoutWidget = QtGui.QWidget(Mapmaker)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 1121, 830))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.CenterLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.CenterLayout.setMargin(0)
        self.CenterLayout.setObjectName(_fromUtf8("CenterLayout"))
        self.formLayoutWidget_2 = QtGui.QWidget(Mapmaker)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(1140, 520, 201, 161))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.LogoLayout = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.LogoLayout.setMargin(0)
        self.LogoLayout.setObjectName(_fromUtf8("LogoLayout"))
        self.label.setBuddy(self.SymmetryComboBox)
        self.label_3.setBuddy(self.RowLineEdit)
        self.label_4.setBuddy(self.ColumnLineEdit)

        self.retranslateUi(Mapmaker)
        self.UnitTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Mapmaker)

    def retranslateUi(self, Mapmaker):
        Mapmaker.setWindowTitle(_translate("Mapmaker", "Form", None))
        self.label.setText(_translate("Mapmaker", "对称方式：", None))
        self.SymmetryComboBox.setItemText(0, _translate("Mapmaker", "左右对称", None))
        self.SymmetryComboBox.setItemText(1, _translate("Mapmaker", "上下对称", None))
        self.SymmetryComboBox.setItemText(2, _translate("Mapmaker", "中心对称", None))
        self.label_2.setText(_translate("Mapmaker", "地图大小：", None))
        self.label_5.setText(_translate("Mapmaker", "地形元素：", None))
        self.BaseRadioButton.setText(_translate("Mapmaker", "基地岛", None))
        self.MineRadioButton.setText(_translate("Mapmaker", "矿产岛", None))
        self.OilRadioButton.setText(_translate("Mapmaker", "油田岛", None))
        self.SurfaceRadioButton.setText(_translate("Mapmaker", "水面", None))
        self.IslandRadioButton.setText(_translate("Mapmaker", "普通岛屿", None))
        self.DeleteTerrainRadioButton.setText(_translate("Mapmaker", "删除地形", None))
        self.label_3.setText(_translate("Mapmaker", "行数：", None))
        self.label_4.setText(_translate("Mapmaker", "列数：", None))
        self.UnitTabWidget.setTabText(self.UnitTabWidget.indexOf(self.MapUnitTab), _translate("Mapmaker", "地形", None))
        self.label_6.setText(_translate("Mapmaker", "组成（战斗/鱼雷/轰炸/侦查)", None))
        self.DeleteUnitRadioButton.setText(_translate("Mapmaker", "删除单位", None))
        self.SubmarineRadioButton.setText(_translate("Mapmaker", "潜艇", None))
        self.DestroyerRadioButton.setText(_translate("Mapmaker", "驱逐舰", None))
        self.CruiserRadioButton.setText(_translate("Mapmaker", "巡洋舰", None))
        self.BattleshipRadioButton.setText(_translate("Mapmaker", "战列舰", None))
        self.CarrierRadioButton.setText(_translate("Mapmaker", "航空母舰", None))
        self.CargoRadioButton.setText(_translate("Mapmaker", "运输舰", None))
        self.FormationRadioButton.setText(_translate("Mapmaker", "飞机编队", None))
        self.UnitTabWidget.setTabText(self.UnitTabWidget.indexOf(self.SoldierUnitTab), _translate("Mapmaker", "单位", None))
        self.ExitButton.setText(_translate("Mapmaker", "后退", None))
        self.HelpButton.setText(_translate("Mapmaker", "帮助", None))
        self.NewFileButton.setText(_translate("Mapmaker", "新建", None))
        self.OpenFileButton.setText(_translate("Mapmaker", "打开", None))
        self.SaveButton.setText(_translate("Mapmaker", "保存", None))
        self.SaveAsButton.setText(_translate("Mapmaker", "另存为", None))
        self.RandomButton.setText(_translate("Mapmaker", "随机生成", None))

