# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameInfo1.ui'
#
# Created: Mon Mar 16 21:37:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GameInfo1(object):
    def setupUi(self, GameInfo1):
        GameInfo1.setObjectName(_fromUtf8("GameInfo1"))
        GameInfo1.resize(250, 274)
        self.label_25 = QtGui.QLabel(GameInfo1)
        self.label_25.setGeometry(QtCore.QRect(180, 40, 54, 12))
        self.label_25.setStyleSheet(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.layoutWidget = QtGui.QWidget(GameInfo1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 231, 24))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.RoundNumberLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.RoundNumberLineEdit.setStyleSheet(_fromUtf8(""))
        self.RoundNumberLineEdit.setReadOnly(True)
        self.RoundNumberLineEdit.setObjectName(_fromUtf8("RoundNumberLineEdit"))
        self.horizontalLayout_7.addWidget(self.RoundNumberLineEdit)
        self.label_24 = QtGui.QLabel(GameInfo1)
        self.label_24.setGeometry(QtCore.QRect(110, 40, 54, 12))
        self.label_24.setStyleSheet(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.layoutWidget1 = QtGui.QWidget(GameInfo1)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 231, 211))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.PeopleNumberLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.PeopleNumberLineEdit1.setStyleSheet(_fromUtf8(""))
        self.PeopleNumberLineEdit1.setReadOnly(True)
        self.PeopleNumberLineEdit1.setObjectName(_fromUtf8("PeopleNumberLineEdit1"))
        self.gridLayout.addWidget(self.PeopleNumberLineEdit1, 0, 1, 1, 1)
        self.PeopleNumberLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.PeopleNumberLineEdit2.setStyleSheet(_fromUtf8(""))
        self.PeopleNumberLineEdit2.setReadOnly(True)
        self.PeopleNumberLineEdit2.setObjectName(_fromUtf8("PeopleNumberLineEdit2"))
        self.gridLayout.addWidget(self.PeopleNumberLineEdit2, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.ScoreLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.ScoreLineEdit1.setReadOnly(True)
        self.ScoreLineEdit1.setObjectName(_fromUtf8("ScoreLineEdit1"))
        self.gridLayout.addWidget(self.ScoreLineEdit1, 1, 1, 1, 1)
        self.ScoreLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.ScoreLineEdit2.setReadOnly(True)
        self.ScoreLineEdit2.setObjectName(_fromUtf8("ScoreLineEdit2"))
        self.gridLayout.addWidget(self.ScoreLineEdit2, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setStyleSheet(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.SourceNumberLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.SourceNumberLineEdit1.setStyleSheet(_fromUtf8(""))
        self.SourceNumberLineEdit1.setReadOnly(True)
        self.SourceNumberLineEdit1.setObjectName(_fromUtf8("SourceNumberLineEdit1"))
        self.gridLayout.addWidget(self.SourceNumberLineEdit1, 2, 1, 1, 1)
        self.SourceNumberLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.SourceNumberLineEdit2.setStyleSheet(_fromUtf8(""))
        self.SourceNumberLineEdit2.setReadOnly(True)
        self.SourceNumberLineEdit2.setObjectName(_fromUtf8("SourceNumberLineEdit2"))
        self.gridLayout.addWidget(self.SourceNumberLineEdit2, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.BaseLifeLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.BaseLifeLineEdit1.setStyleSheet(_fromUtf8(""))
        self.BaseLifeLineEdit1.setReadOnly(True)
        self.BaseLifeLineEdit1.setObjectName(_fromUtf8("BaseLifeLineEdit1"))
        self.gridLayout.addWidget(self.BaseLifeLineEdit1, 3, 1, 1, 1)
        self.BaseLifeLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.BaseLifeLineEdit2.setStyleSheet(_fromUtf8(""))
        self.BaseLifeLineEdit2.setReadOnly(True)
        self.BaseLifeLineEdit2.setObjectName(_fromUtf8("BaseLifeLineEdit2"))
        self.gridLayout.addWidget(self.BaseLifeLineEdit2, 3, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setStyleSheet(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.PlaneNumberLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.PlaneNumberLineEdit1.setStyleSheet(_fromUtf8(""))
        self.PlaneNumberLineEdit1.setReadOnly(True)
        self.PlaneNumberLineEdit1.setObjectName(_fromUtf8("PlaneNumberLineEdit1"))
        self.gridLayout.addWidget(self.PlaneNumberLineEdit1, 4, 1, 1, 1)
        self.PlaneNumberLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.PlaneNumberLineEdit2.setStyleSheet(_fromUtf8(""))
        self.PlaneNumberLineEdit2.setReadOnly(True)
        self.PlaneNumberLineEdit2.setObjectName(_fromUtf8("PlaneNumberLineEdit2"))
        self.gridLayout.addWidget(self.PlaneNumberLineEdit2, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.ShipNumberLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.ShipNumberLineEdit1.setStyleSheet(_fromUtf8(""))
        self.ShipNumberLineEdit1.setReadOnly(True)
        self.ShipNumberLineEdit1.setObjectName(_fromUtf8("ShipNumberLineEdit1"))
        self.gridLayout.addWidget(self.ShipNumberLineEdit1, 5, 1, 1, 1)
        self.ShipNumberLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.ShipNumberLineEdit2.setStyleSheet(_fromUtf8(""))
        self.ShipNumberLineEdit2.setReadOnly(True)
        self.ShipNumberLineEdit2.setObjectName(_fromUtf8("ShipNumberLineEdit2"))
        self.gridLayout.addWidget(self.ShipNumberLineEdit2, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setStyleSheet(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.SubmarineNumberLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.SubmarineNumberLineEdit1.setStyleSheet(_fromUtf8(""))
        self.SubmarineNumberLineEdit1.setReadOnly(True)
        self.SubmarineNumberLineEdit1.setObjectName(_fromUtf8("SubmarineNumberLineEdit1"))
        self.gridLayout.addWidget(self.SubmarineNumberLineEdit1, 6, 1, 1, 1)
        self.SubmarineNumberLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.SubmarineNumberLineEdit2.setStyleSheet(_fromUtf8(""))
        self.SubmarineNumberLineEdit2.setReadOnly(True)
        self.SubmarineNumberLineEdit2.setObjectName(_fromUtf8("SubmarineNumberLineEdit2"))
        self.gridLayout.addWidget(self.SubmarineNumberLineEdit2, 6, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.FortNumberLineEdit1 = QtGui.QLineEdit(self.layoutWidget1)
        self.FortNumberLineEdit1.setStyleSheet(_fromUtf8(""))
        self.FortNumberLineEdit1.setReadOnly(True)
        self.FortNumberLineEdit1.setObjectName(_fromUtf8("FortNumberLineEdit1"))
        self.gridLayout.addWidget(self.FortNumberLineEdit1, 7, 1, 1, 1)
        self.FortNumberLineEdit2 = QtGui.QLineEdit(self.layoutWidget1)
        self.FortNumberLineEdit2.setStyleSheet(_fromUtf8(""))
        self.FortNumberLineEdit2.setReadOnly(True)
        self.FortNumberLineEdit2.setObjectName(_fromUtf8("FortNumberLineEdit2"))
        self.gridLayout.addWidget(self.FortNumberLineEdit2, 7, 2, 1, 1)
        self.label.setBuddy(self.RoundNumberLineEdit)
        self.label_8.setBuddy(self.SourceNumberLineEdit1)
        self.label_7.setBuddy(self.BaseLifeLineEdit1)
        self.label_3.setBuddy(self.PlaneNumberLineEdit1)
        self.label_4.setBuddy(self.ShipNumberLineEdit1)
        self.label_5.setBuddy(self.SubmarineNumberLineEdit1)

        self.retranslateUi(GameInfo1)
        QtCore.QMetaObject.connectSlotsByName(GameInfo1)

    def retranslateUi(self, GameInfo1):
        GameInfo1.setWindowTitle(_translate("GameInfo1", "游戏信息", None))
        self.label_25.setText(_translate("GameInfo1", "   1号", None))
        self.label.setText(_translate("GameInfo1", "回合数       ：", None))
        self.label_24.setText(_translate("GameInfo1", "   0号", None))
        self.label_2.setText(_translate("GameInfo1", "人口数       ：", None))
        self.label_9.setText(_translate("GameInfo1", "积分         ：", None))
        self.label_8.setText(_translate("GameInfo1", "资源(金/油)  ：", None))
        self.label_7.setText(_translate("GameInfo1", "基地生命     ：", None))
        self.label_3.setText(_translate("GameInfo1", "空中单位数   ：", None))
        self.label_4.setText(_translate("GameInfo1", "水面单位数   ：", None))
        self.label_5.setText(_translate("GameInfo1", "水下单位数   ：", None))
        self.label_6.setText(_translate("GameInfo1", "岛屿数       ：", None))

