# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameInfo2.ui'
#
# Created: Tue Dec 23 00:50:14 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GameInfo2(object):
    def setupUi(self, GameInfo2):
        GameInfo2.setObjectName(_fromUtf8("GameInfo2"))
        GameInfo2.resize(235, 427)
        self.layoutWidget = QtGui.QWidget(GameInfo2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 411))
        self.layoutWidget.setStyleSheet(_fromUtf8(""))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.AmmoLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.AmmoLineEdit.setStyleSheet(_fromUtf8(""))
        self.AmmoLineEdit.setReadOnly(True)
        self.AmmoLineEdit.setObjectName(_fromUtf8("AmmoLineEdit"))
        self.gridLayout_2.addWidget(self.AmmoLineEdit, 8, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setStyleSheet(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 13, 0, 1, 1)
        self.DefenceLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.DefenceLineEdit.setStyleSheet(_fromUtf8(""))
        self.DefenceLineEdit.setReadOnly(True)
        self.DefenceLineEdit.setObjectName(_fromUtf8("DefenceLineEdit"))
        self.gridLayout_2.addWidget(self.DefenceLineEdit, 4, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setStyleSheet(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 9, 0, 1, 1)
        self.HealthLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.HealthLineEdit.setStyleSheet(_fromUtf8(""))
        self.HealthLineEdit.setReadOnly(True)
        self.HealthLineEdit.setObjectName(_fromUtf8("HealthLineEdit"))
        self.gridLayout_2.addWidget(self.HealthLineEdit, 5, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setStyleSheet(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setStyleSheet(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setStyleSheet(_fromUtf8(""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 12, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setStyleSheet(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 8, 0, 1, 1)
        self.FuelLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.FuelLineEdit.setStyleSheet(_fromUtf8(""))
        self.FuelLineEdit.setReadOnly(True)
        self.FuelLineEdit.setObjectName(_fromUtf8("FuelLineEdit"))
        self.gridLayout_2.addWidget(self.FuelLineEdit, 7, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 16, 0, 1, 1)
        self.FireRangeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.FireRangeLineEdit.setStyleSheet(_fromUtf8(""))
        self.FireRangeLineEdit.setObjectName(_fromUtf8("FireRangeLineEdit"))
        self.gridLayout_2.addWidget(self.FireRangeLineEdit, 10, 2, 1, 1)
        self.SightRangeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.SightRangeLineEdit.setStyleSheet(_fromUtf8(""))
        self.SightRangeLineEdit.setReadOnly(True)
        self.SightRangeLineEdit.setObjectName(_fromUtf8("SightRangeLineEdit"))
        self.gridLayout_2.addWidget(self.SightRangeLineEdit, 9, 2, 1, 1)
        self.MoveTargetLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.MoveTargetLineEdit.setStyleSheet(_fromUtf8(""))
        self.MoveTargetLineEdit.setReadOnly(True)
        self.MoveTargetLineEdit.setObjectName(_fromUtf8("MoveTargetLineEdit"))
        self.gridLayout_2.addWidget(self.MoveTargetLineEdit, 12, 2, 1, 1)
        self.TerrainLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.TerrainLineEdit.setStyleSheet(_fromUtf8(""))
        self.TerrainLineEdit.setObjectName(_fromUtf8("TerrainLineEdit"))
        self.gridLayout_2.addWidget(self.TerrainLineEdit, 15, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 10, 0, 1, 1)
        self.CoordinateLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.CoordinateLineEdit.setStyleSheet(_fromUtf8(""))
        self.CoordinateLineEdit.setObjectName(_fromUtf8("CoordinateLineEdit"))
        self.gridLayout_2.addWidget(self.CoordinateLineEdit, 16, 2, 1, 1)
        self.TypeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.TypeLineEdit.setStyleSheet(_fromUtf8(""))
        self.TypeLineEdit.setReadOnly(True)
        self.TypeLineEdit.setObjectName(_fromUtf8("TypeLineEdit"))
        self.gridLayout_2.addWidget(self.TypeLineEdit, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setStyleSheet(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 15, 0, 1, 1)
        self.SpeedLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.SpeedLineEdit.setStyleSheet(_fromUtf8(""))
        self.SpeedLineEdit.setReadOnly(True)
        self.SpeedLineEdit.setObjectName(_fromUtf8("SpeedLineEdit"))
        self.gridLayout_2.addWidget(self.SpeedLineEdit, 6, 2, 1, 1)
        self.AttackLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.AttackLineEdit.setStyleSheet(_fromUtf8(""))
        self.AttackLineEdit.setReadOnly(True)
        self.AttackLineEdit.setObjectName(_fromUtf8("AttackLineEdit"))
        self.gridLayout_2.addWidget(self.AttackLineEdit, 3, 2, 1, 1)
        self.PopulationLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.PopulationLineEdit.setStyleSheet(_fromUtf8(""))
        self.PopulationLineEdit.setReadOnly(True)
        self.PopulationLineEdit.setObjectName(_fromUtf8("PopulationLineEdit"))
        self.gridLayout_2.addWidget(self.PopulationLineEdit, 13, 2, 1, 1)
        self.CarrySourceLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.CarrySourceLineEdit.setStyleSheet(_fromUtf8(""))
        self.CarrySourceLineEdit.setReadOnly(True)
        self.CarrySourceLineEdit.setObjectName(_fromUtf8("CarrySourceLineEdit"))
        self.gridLayout_2.addWidget(self.CarrySourceLineEdit, 11, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setStyleSheet(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 14, 0, 1, 1)
        self.NeedMetalLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.NeedMetalLineEdit.setStyleSheet(_fromUtf8(""))
        self.NeedMetalLineEdit.setObjectName(_fromUtf8("NeedMetalLineEdit"))
        self.gridLayout_2.addWidget(self.NeedMetalLineEdit, 14, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.TeamLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.TeamLineEdit.setStyleSheet(_fromUtf8(""))
        self.TeamLineEdit.setReadOnly(True)
        self.TeamLineEdit.setObjectName(_fromUtf8("TeamLineEdit"))
        self.gridLayout_2.addWidget(self.TeamLineEdit, 2, 2, 1, 1)
        self.label_13.setBuddy(self.HealthLineEdit)
        self.label_17.setBuddy(self.SightRangeLineEdit)
        self.label_14.setBuddy(self.FuelLineEdit)
        self.label_16.setBuddy(self.CarrySourceLineEdit)
        self.label_18.setBuddy(self.MoveTargetLineEdit)
        self.label_15.setBuddy(self.AmmoLineEdit)
        self.label_9.setBuddy(self.AttackLineEdit)
        self.label_6.setBuddy(self.TypeLineEdit)
        self.label_10.setBuddy(self.DefenceLineEdit)
        self.label_11.setBuddy(self.SpeedLineEdit)

        self.retranslateUi(GameInfo2)
        QtCore.QMetaObject.connectSlotsByName(GameInfo2)

    def retranslateUi(self, GameInfo2):
        GameInfo2.setWindowTitle(_translate("GameInfo2", "单位信息", None))
        self.label_13.setText(_translate("GameInfo2", "血量：", None))
        self.label_5.setText(_translate("GameInfo2", "人口数：", None))
        self.label_17.setText(_translate("GameInfo2", "视野：", None))
        self.label_14.setText(_translate("GameInfo2", "燃料：", None))
        self.label_16.setText(_translate("GameInfo2", "金属：", None))
        self.label_18.setText(_translate("GameInfo2", "移动目标：", None))
        self.label_15.setText(_translate("GameInfo2", "弹药：", None))
        self.label.setText(_translate("GameInfo2", "坐标：", None))
        self.label_2.setText(_translate("GameInfo2", "攻击范围：", None))
        self.label_9.setText(_translate("GameInfo2", "攻击力：", None))
        self.label_3.setText(_translate("GameInfo2", "地形：", None))
        self.label_6.setText(_translate("GameInfo2", "种类：", None))
        self.label_10.setText(_translate("GameInfo2", "防御力：", None))
        self.label_4.setText(_translate("GameInfo2", "所需金属：", None))
        self.label_11.setText(_translate("GameInfo2", "速度：", None))
        self.label_7.setText(_translate("GameInfo2", "队伍：", None))

