# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameInfo2.ui'
#
# Created: Tue Sep 16 20:41:36 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GameInfo2(object):
    def setupUi(self, GameInfo2):
        GameInfo2.setObjectName(_fromUtf8("GameInfo2"))
        GameInfo2.resize(235, 459)
        self.layoutWidget = QtGui.QWidget(GameInfo2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 438))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.TypeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.TypeLineEdit.setReadOnly(True)
        self.TypeLineEdit.setObjectName(_fromUtf8("TypeLineEdit"))
        self.gridLayout_2.addWidget(self.TypeLineEdit, 1, 2, 1, 1)
        self.TerrainLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.TerrainLineEdit.setObjectName(_fromUtf8("TerrainLineEdit"))
        self.gridLayout_2.addWidget(self.TerrainLineEdit, 15, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 17, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 13, 0, 1, 1)
        self.AttackLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.AttackLineEdit.setReadOnly(True)
        self.AttackLineEdit.setObjectName(_fromUtf8("AttackLineEdit"))
        self.gridLayout_2.addWidget(self.AttackLineEdit, 3, 2, 1, 1)
        self.CommandLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.CommandLineEdit.setReadOnly(True)
        self.CommandLineEdit.setObjectName(_fromUtf8("CommandLineEdit"))
        self.gridLayout_2.addWidget(self.CommandLineEdit, 14, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 14, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 15, 0, 1, 1)
        self.CarrySourceLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.CarrySourceLineEdit.setReadOnly(True)
        self.CarrySourceLineEdit.setObjectName(_fromUtf8("CarrySourceLineEdit"))
        self.gridLayout_2.addWidget(self.CarrySourceLineEdit, 11, 2, 1, 1)
        self.SourceLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.SourceLineEdit.setObjectName(_fromUtf8("SourceLineEdit"))
        self.gridLayout_2.addWidget(self.SourceLineEdit, 17, 2, 1, 1)
        self.SpeedLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.SpeedLineEdit.setReadOnly(True)
        self.SpeedLineEdit.setObjectName(_fromUtf8("SpeedLineEdit"))
        self.gridLayout_2.addWidget(self.SpeedLineEdit, 6, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.HealthLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.HealthLineEdit.setReadOnly(True)
        self.HealthLineEdit.setObjectName(_fromUtf8("HealthLineEdit"))
        self.gridLayout_2.addWidget(self.HealthLineEdit, 5, 2, 1, 1)
        self.AmmoLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.AmmoLineEdit.setReadOnly(True)
        self.AmmoLineEdit.setObjectName(_fromUtf8("AmmoLineEdit"))
        self.gridLayout_2.addWidget(self.AmmoLineEdit, 8, 2, 1, 1)
        self.DefenceLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.DefenceLineEdit.setReadOnly(True)
        self.DefenceLineEdit.setObjectName(_fromUtf8("DefenceLineEdit"))
        self.gridLayout_2.addWidget(self.DefenceLineEdit, 4, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 9, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.PlaneTypeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.PlaneTypeLineEdit.setReadOnly(True)
        self.PlaneTypeLineEdit.setObjectName(_fromUtf8("PlaneTypeLineEdit"))
        self.gridLayout_2.addWidget(self.PlaneTypeLineEdit, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 12, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 8, 0, 1, 1)
        self.SightRangeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.SightRangeLineEdit.setReadOnly(True)
        self.SightRangeLineEdit.setObjectName(_fromUtf8("SightRangeLineEdit"))
        self.gridLayout_2.addWidget(self.SightRangeLineEdit, 9, 2, 1, 1)
        self.FuelLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.FuelLineEdit.setReadOnly(True)
        self.FuelLineEdit.setObjectName(_fromUtf8("FuelLineEdit"))
        self.gridLayout_2.addWidget(self.FuelLineEdit, 7, 2, 1, 1)
        self.AttackTargetLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.AttackTargetLineEdit.setReadOnly(True)
        self.AttackTargetLineEdit.setObjectName(_fromUtf8("AttackTargetLineEdit"))
        self.gridLayout_2.addWidget(self.AttackTargetLineEdit, 13, 2, 1, 1)
        self.MoveTargetLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.MoveTargetLineEdit.setReadOnly(True)
        self.MoveTargetLineEdit.setObjectName(_fromUtf8("MoveTargetLineEdit"))
        self.gridLayout_2.addWidget(self.MoveTargetLineEdit, 12, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 16, 0, 1, 1)
        self.CoordinateLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.CoordinateLineEdit.setObjectName(_fromUtf8("CoordinateLineEdit"))
        self.gridLayout_2.addWidget(self.CoordinateLineEdit, 16, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 10, 0, 1, 1)
        self.FireRangeLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.FireRangeLineEdit.setObjectName(_fromUtf8("FireRangeLineEdit"))
        self.gridLayout_2.addWidget(self.FireRangeLineEdit, 10, 2, 1, 1)
        self.label_9.setBuddy(self.AttackLineEdit)
        self.label_21.setBuddy(self.SourceLineEdit)
        self.label_6.setBuddy(self.TypeLineEdit)
        self.label_19.setBuddy(self.AttackTargetLineEdit)
        self.label_23.setBuddy(self.CommandLineEdit)
        self.label_20.setBuddy(self.TerrainLineEdit)
        self.label_11.setBuddy(self.SpeedLineEdit)
        self.label_12.setBuddy(self.PlaneTypeLineEdit)
        self.label_10.setBuddy(self.DefenceLineEdit)
        self.label_17.setBuddy(self.SightRangeLineEdit)
        self.label_13.setBuddy(self.HealthLineEdit)
        self.label_14.setBuddy(self.FuelLineEdit)
        self.label_18.setBuddy(self.MoveTargetLineEdit)
        self.label_16.setBuddy(self.CarrySourceLineEdit)
        self.label_15.setBuddy(self.AmmoLineEdit)

        self.retranslateUi(GameInfo2)
        QtCore.QMetaObject.connectSlotsByName(GameInfo2)

    def retranslateUi(self, GameInfo2):
        GameInfo2.setWindowTitle(_translate("GameInfo2", "单位信息", None))
        self.label_9.setText(_translate("GameInfo2", "攻击力：", None))
        self.label_21.setText(_translate("GameInfo2", "资源：    ", None))
        self.label_6.setText(_translate("GameInfo2", "种类：", None))
        self.label_19.setText(_translate("GameInfo2", "攻击目标：", None))
        self.label_23.setText(_translate("GameInfo2", "指令：", None))
        self.label_20.setText(_translate("GameInfo2", "地形：      ", None))
        self.label_11.setText(_translate("GameInfo2", "速度：", None))
        self.label_12.setText(_translate("GameInfo2", "机群构成：  ", None))
        self.label_10.setText(_translate("GameInfo2", "防御力：", None))
        self.label_17.setText(_translate("GameInfo2", "视野：", None))
        self.label_13.setText(_translate("GameInfo2", "血量：", None))
        self.label_14.setText(_translate("GameInfo2", "燃料：", None))
        self.label_18.setText(_translate("GameInfo2", "移动目标：", None))
        self.label_16.setText(_translate("GameInfo2", "携带资源：", None))
        self.label_15.setText(_translate("GameInfo2", "弹药：", None))
        self.label.setText(_translate("GameInfo2", "坐标：", None))
        self.label_2.setText(_translate("GameInfo2", "攻击范围：", None))

