# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mapmaker.ui'
#
# Created: Sun Dec 21 19:25:32 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mapmaker(object):
    def setupUi(self, Mapmaker):
        Mapmaker.setObjectName(_fromUtf8("Mapmaker"))
        Mapmaker.resize(1344, 768)
        self.formLayoutWidget = QtGui.QWidget(Mapmaker)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 0, 1031, 771))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.CenterLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.CenterLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.CenterLayout.setContentsMargins(-1, -1, 0, -1)
        self.CenterLayout.setSpacing(0)
        self.CenterLayout.setObjectName(_fromUtf8("CenterLayout"))
        self.layoutWidget = QtGui.QWidget(Mapmaker)
        self.layoutWidget.setGeometry(QtCore.QRect(1140, 190, 167, 221))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setStyleSheet(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.CarrierLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.CarrierLineEdit.setStyleSheet(_fromUtf8(""))
        self.CarrierLineEdit.setObjectName(_fromUtf8("CarrierLineEdit"))
        self.gridLayout.addWidget(self.CarrierLineEdit, 2, 1, 1, 1)
        self.FighterLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.FighterLineEdit.setStyleSheet(_fromUtf8(""))
        self.FighterLineEdit.setObjectName(_fromUtf8("FighterLineEdit"))
        self.gridLayout.addWidget(self.FighterLineEdit, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.DestroyerLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.DestroyerLineEdit.setStyleSheet(_fromUtf8(""))
        self.DestroyerLineEdit.setObjectName(_fromUtf8("DestroyerLineEdit"))
        self.gridLayout.addWidget(self.DestroyerLineEdit, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setStyleSheet(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.ScoutLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.ScoutLineEdit.setAutoFillBackground(False)
        self.ScoutLineEdit.setStyleSheet(_fromUtf8(""))
        self.ScoutLineEdit.setObjectName(_fromUtf8("ScoutLineEdit"))
        self.gridLayout.addWidget(self.ScoutLineEdit, 5, 1, 1, 1)
        self.SubmarineLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.SubmarineLineEdit.setStyleSheet(_fromUtf8(""))
        self.SubmarineLineEdit.setObjectName(_fromUtf8("SubmarineLineEdit"))
        self.gridLayout.addWidget(self.SubmarineLineEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.CargoLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.CargoLineEdit.setStyleSheet(_fromUtf8(""))
        self.CargoLineEdit.setObjectName(_fromUtf8("CargoLineEdit"))
        self.gridLayout.addWidget(self.CargoLineEdit, 3, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(Mapmaker)
        self.layoutWidget1.setGeometry(QtCore.QRect(1140, 50, 168, 108))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.SizeCombo = QtGui.QComboBox(self.layoutWidget1)
        self.SizeCombo.setStyleSheet(_fromUtf8(""))
        self.SizeCombo.setObjectName(_fromUtf8("SizeCombo"))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.SizeCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.SizeCombo, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setStyleSheet(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.LandCombo = QtGui.QComboBox(self.layoutWidget1)
        self.LandCombo.setStyleSheet(_fromUtf8(""))
        self.LandCombo.setObjectName(_fromUtf8("LandCombo"))
        self.LandCombo.addItem(_fromUtf8(""))
        self.LandCombo.addItem(_fromUtf8(""))
        self.LandCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.LandCombo, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setStyleSheet(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.SourceCombo = QtGui.QComboBox(self.layoutWidget1)
        self.SourceCombo.setStyleSheet(_fromUtf8(""))
        self.SourceCombo.setObjectName(_fromUtf8("SourceCombo"))
        self.SourceCombo.addItem(_fromUtf8(""))
        self.SourceCombo.addItem(_fromUtf8(""))
        self.SourceCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.SourceCombo, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.CenterCombo = QtGui.QComboBox(self.layoutWidget1)
        self.CenterCombo.setStyleSheet(_fromUtf8(""))
        self.CenterCombo.setObjectName(_fromUtf8("CenterCombo"))
        self.CenterCombo.addItem(_fromUtf8(""))
        self.CenterCombo.addItem(_fromUtf8(""))
        self.CenterCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.CenterCombo, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(Mapmaker)
        self.label_13.setGeometry(QtCore.QRect(1140, 170, 161, 16))
        self.label_13.setStyleSheet(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.RandomButton = QtGui.QPushButton(Mapmaker)
        self.RandomButton.setGeometry(QtCore.QRect(1230, 550, 75, 23))
        self.RandomButton.setStyleSheet(_fromUtf8(""))
        self.RandomButton.setObjectName(_fromUtf8("RandomButton"))
        self.SaveButton = QtGui.QPushButton(Mapmaker)
        self.SaveButton.setGeometry(QtCore.QRect(1140, 550, 75, 23))
        self.SaveButton.setStyleSheet(_fromUtf8(""))
        self.SaveButton.setObjectName(_fromUtf8("SaveButton"))
        self.ExitButton = QtGui.QPushButton(Mapmaker)
        self.ExitButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.ExitButton.setStyleSheet(_fromUtf8(""))
        self.ExitButton.setObjectName(_fromUtf8("ExitButton"))
        self.HelpButton = QtGui.QPushButton(Mapmaker)
        self.HelpButton.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.HelpButton.setStyleSheet(_fromUtf8(""))
        self.HelpButton.setObjectName(_fromUtf8("HelpButton"))
        self.label_14 = QtGui.QLabel(Mapmaker)
        self.label_14.setGeometry(QtCore.QRect(1150, 610, 54, 12))
        self.label_14.setStyleSheet(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.layoutWidget2 = QtGui.QWidget(Mapmaker)
        self.layoutWidget2.setGeometry(QtCore.QRect(1140, 430, 191, 66))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.PopulationLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.PopulationLineEdit.setStyleSheet(_fromUtf8(""))
        self.PopulationLineEdit.setObjectName(_fromUtf8("PopulationLineEdit"))
        self.gridLayout_3.addWidget(self.PopulationLineEdit, 0, 1, 1, 1)
        self.RoundLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.RoundLineEdit.setStyleSheet(_fromUtf8(""))
        self.RoundLineEdit.setObjectName(_fromUtf8("RoundLineEdit"))
        self.gridLayout_3.addWidget(self.RoundLineEdit, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget2)
        self.label_12.setStyleSheet(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(Mapmaker)
        self.label_15.setGeometry(QtCore.QRect(1140, 510, 81, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.WeatherLineEdit = QtGui.QLineEdit(Mapmaker)
        self.WeatherLineEdit.setGeometry(QtCore.QRect(1220, 510, 113, 20))
        self.WeatherLineEdit.setObjectName(_fromUtf8("WeatherLineEdit"))
        self.UpPushButton = QtGui.QPushButton(Mapmaker)
        self.UpPushButton.setGeometry(QtCore.QRect(1190, 590, 75, 23))
        self.UpPushButton.setObjectName(_fromUtf8("UpPushButton"))
        self.DownPushButton = QtGui.QPushButton(Mapmaker)
        self.DownPushButton.setGeometry(QtCore.QRect(1190, 620, 75, 23))
        self.DownPushButton.setObjectName(_fromUtf8("DownPushButton"))

        self.retranslateUi(Mapmaker)
        QtCore.QMetaObject.connectSlotsByName(Mapmaker)
        Mapmaker.setTabOrder(self.SizeCombo, self.LandCombo)
        Mapmaker.setTabOrder(self.LandCombo, self.SourceCombo)
        Mapmaker.setTabOrder(self.SourceCombo, self.CenterCombo)
        Mapmaker.setTabOrder(self.CenterCombo, self.SubmarineLineEdit)
        Mapmaker.setTabOrder(self.SubmarineLineEdit, self.DestroyerLineEdit)
        Mapmaker.setTabOrder(self.DestroyerLineEdit, self.CarrierLineEdit)
        Mapmaker.setTabOrder(self.CarrierLineEdit, self.CargoLineEdit)
        Mapmaker.setTabOrder(self.CargoLineEdit, self.FighterLineEdit)
        Mapmaker.setTabOrder(self.FighterLineEdit, self.ScoutLineEdit)
        Mapmaker.setTabOrder(self.ScoutLineEdit, self.PopulationLineEdit)
        Mapmaker.setTabOrder(self.PopulationLineEdit, self.RoundLineEdit)
        Mapmaker.setTabOrder(self.RoundLineEdit, self.WeatherLineEdit)
        Mapmaker.setTabOrder(self.WeatherLineEdit, self.SaveButton)
        Mapmaker.setTabOrder(self.SaveButton, self.RandomButton)
        Mapmaker.setTabOrder(self.RandomButton, self.ExitButton)
        Mapmaker.setTabOrder(self.ExitButton, self.HelpButton)

    def retranslateUi(self, Mapmaker):
        Mapmaker.setWindowTitle(_translate("Mapmaker", "Form", None))
        self.label_10.setText(_translate("Mapmaker", "战斗机数：", None))
        self.CarrierLineEdit.setText(_translate("Mapmaker", "0", None))
        self.FighterLineEdit.setText(_translate("Mapmaker", "0", None))
        self.label_11.setText(_translate("Mapmaker", "侦察机数：", None))
        self.label_5.setText(_translate("Mapmaker", "潜艇数：", None))
        self.DestroyerLineEdit.setText(_translate("Mapmaker", "0", None))
        self.label_9.setText(_translate("Mapmaker", "运输舰数：", None))
        self.label_8.setText(_translate("Mapmaker", "航母数：", None))
        self.ScoutLineEdit.setText(_translate("Mapmaker", "0", None))
        self.SubmarineLineEdit.setText(_translate("Mapmaker", "0", None))
        self.label_7.setText(_translate("Mapmaker", "驱逐舰数：", None))
        self.CargoLineEdit.setText(_translate("Mapmaker", "0", None))
        self.label_2.setText(_translate("Mapmaker", "地图大小：", None))
        self.SizeCombo.setItemText(0, _translate("Mapmaker", "30*30", None))
        self.SizeCombo.setItemText(1, _translate("Mapmaker", "40*40", None))
        self.SizeCombo.setItemText(2, _translate("Mapmaker", "50*50", None))
        self.SizeCombo.setItemText(3, _translate("Mapmaker", "60*60", None))
        self.SizeCombo.setItemText(4, _translate("Mapmaker", "70*70", None))
        self.SizeCombo.setItemText(5, _translate("Mapmaker", "80*80", None))
        self.SizeCombo.setItemText(6, _translate("Mapmaker", "90*90", None))
        self.SizeCombo.setItemText(7, _translate("Mapmaker", "100*100", None))
        self.label_3.setText(_translate("Mapmaker", "陆地比例：", None))
        self.LandCombo.setItemText(0, _translate("Mapmaker", "少", None))
        self.LandCombo.setItemText(1, _translate("Mapmaker", "中", None))
        self.LandCombo.setItemText(2, _translate("Mapmaker", "多", None))
        self.label_4.setText(_translate("Mapmaker", "资源数：", None))
        self.SourceCombo.setItemText(0, _translate("Mapmaker", "少", None))
        self.SourceCombo.setItemText(1, _translate("Mapmaker", "中", None))
        self.SourceCombo.setItemText(2, _translate("Mapmaker", "多", None))
        self.label.setText(_translate("Mapmaker", "对称方式：", None))
        self.CenterCombo.setItemText(0, _translate("Mapmaker", "左右对称", None))
        self.CenterCombo.setItemText(1, _translate("Mapmaker", "上下对称", None))
        self.CenterCombo.setItemText(2, _translate("Mapmaker", "中心对称", None))
        self.label_13.setText(_translate("Mapmaker", "一方参数(各单位数0-10)：", None))
        self.RandomButton.setText(_translate("Mapmaker", "随机生成", None))
        self.SaveButton.setText(_translate("Mapmaker", "保存", None))
        self.ExitButton.setText(_translate("Mapmaker", "后退", None))
        self.HelpButton.setText(_translate("Mapmaker", "帮助", None))
        self.label_14.setText(_translate("Mapmaker", "缩放：", None))
        self.PopulationLineEdit.setText(_translate("Mapmaker", "60", None))
        self.RoundLineEdit.setText(_translate("Mapmaker", "500", None))
        self.label_6.setText(_translate("Mapmaker", "最大回合数(1-1000)：", None))
        self.label_12.setText(_translate("Mapmaker", "最大人口数(30-200)：", None))
        self.label_15.setText(_translate("Mapmaker", "天气（-1~1）：", None))
        self.WeatherLineEdit.setText(_translate("Mapmaker", "0", None))
        self.UpPushButton.setText(_translate("Mapmaker", "↑", None))
        self.DownPushButton.setText(_translate("Mapmaker", "↓", None))

