# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeamWidget.ui'
#
# Created: Tue Sep 23 20:46:36 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TeamWidget(object):
    def setupUi(self, TeamWidget):
        TeamWidget.setObjectName(_fromUtf8("TeamWidget"))
        TeamWidget.resize(602, 400)
        self.label = QtGui.QLabel(TeamWidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label.setStyleSheet(_fromUtf8("font: 16pt \"楷体\";\n"
"color: rgb(42, 14, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_12 = QtGui.QLabel(TeamWidget)
        self.label_12.setGeometry(QtCore.QRect(160, 20, 81, 21))
        self.label_12.setStyleSheet(_fromUtf8("font: 16pt \"楷体\";\n"
"color: rgb(42, 14, 255);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(TeamWidget)
        self.label_13.setGeometry(QtCore.QRect(190, 60, 81, 21))
        self.label_13.setStyleSheet(_fromUtf8("font: 15pt \"楷体\";\n"
"color: rgb(162, 153, 255);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(TeamWidget)
        self.label_14.setGeometry(QtCore.QRect(200, 90, 131, 21))
        self.label_14.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(TeamWidget)
        self.label_15.setGeometry(QtCore.QRect(200, 120, 131, 21))
        self.label_15.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(TeamWidget)
        self.label_16.setGeometry(QtCore.QRect(190, 150, 81, 21))
        self.label_16.setStyleSheet(_fromUtf8("font: 15pt \"楷体\";;\n"
"color: rgb(162, 153, 255);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(TeamWidget)
        self.label_17.setGeometry(QtCore.QRect(200, 180, 131, 21))
        self.label_17.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_19 = QtGui.QLabel(TeamWidget)
        self.label_19.setGeometry(QtCore.QRect(200, 210, 131, 21))
        self.label_19.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(TeamWidget)
        self.label_20.setGeometry(QtCore.QRect(190, 240, 81, 21))
        self.label_20.setStyleSheet(_fromUtf8("font: 15pt \"楷体\";;\n"
"color: rgb(162, 153, 255);"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(TeamWidget)
        self.label_21.setGeometry(QtCore.QRect(200, 270, 131, 21))
        self.label_21.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(TeamWidget)
        self.label_22.setGeometry(QtCore.QRect(200, 300, 131, 21))
        self.label_22.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(TeamWidget)
        self.label_23.setGeometry(QtCore.QRect(380, 60, 81, 21))
        self.label_23.setStyleSheet(_fromUtf8("font: 15pt \"楷体\";;\n"
"color: rgb(162, 153, 255);"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(TeamWidget)
        self.label_24.setGeometry(QtCore.QRect(390, 90, 131, 21))
        self.label_24.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(TeamWidget)
        self.label_25.setGeometry(QtCore.QRect(380, 150, 81, 21))
        self.label_25.setStyleSheet(_fromUtf8("font: 15pt \"楷体\";;\n"
"color: rgb(162, 153, 255);"))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(TeamWidget)
        self.label_26.setGeometry(QtCore.QRect(390, 180, 131, 21))
        self.label_26.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(TeamWidget)
        self.label_27.setGeometry(QtCore.QRect(380, 240, 81, 21))
        self.label_27.setStyleSheet(_fromUtf8("font: 15pt \"楷体\";;\n"
"color: rgb(162, 153, 255);"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(TeamWidget)
        self.label_28.setGeometry(QtCore.QRect(390, 270, 131, 21))
        self.label_28.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(TeamWidget)
        self.label_29.setGeometry(QtCore.QRect(390, 300, 131, 21))
        self.label_29.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.websiteButton = QtGui.QPushButton(TeamWidget)
        self.websiteButton.setGeometry(QtCore.QRect(180, 360, 75, 23))
        self.websiteButton.setObjectName(_fromUtf8("websiteButton"))
        self.ExitButton = QtGui.QPushButton(TeamWidget)
        self.ExitButton.setGeometry(QtCore.QRect(330, 360, 75, 23))
        self.ExitButton.setObjectName(_fromUtf8("ExitButton"))
        self.widget = QtGui.QWidget(TeamWidget)
        self.widget.setGeometry(QtCore.QRect(60, 50, 62, 301))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout.addWidget(self.label_18)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setStyleSheet(_fromUtf8("font: 14pt \"楷体\";"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)

        self.retranslateUi(TeamWidget)
        QtCore.QMetaObject.connectSlotsByName(TeamWidget)

    def retranslateUi(self, TeamWidget):
        TeamWidget.setWindowTitle(_translate("TeamWidget", "Form", None))
        self.label.setText(_translate("TeamWidget", "指导：", None))
        self.label_12.setText(_translate("TeamWidget", "开发组：", None))
        self.label_13.setText(_translate("TeamWidget", "逻辑组", None))
        self.label_14.setText(_translate("TeamWidget", "杨幻睿 郭一隆", None))
        self.label_15.setText(_translate("TeamWidget", "孙胜杨 王殷豪", None))
        self.label_16.setText(_translate("TeamWidget", "平台组", None))
        self.label_17.setText(_translate("TeamWidget", "李思涵 刘家硕", None))
        self.label_19.setText(_translate("TeamWidget", "阮  磊", None))
        self.label_20.setText(_translate("TeamWidget", "展示组", None))
        self.label_21.setText(_translate("TeamWidget", "翁  喆 钟元熠 ", None))
        self.label_22.setText(_translate("TeamWidget", "林圣杰", None))
        self.label_23.setText(_translate("TeamWidget", "网站组", None))
        self.label_24.setText(_translate("TeamWidget", "王健宇 汤皓月", None))
        self.label_25.setText(_translate("TeamWidget", "美工组", None))
        self.label_26.setText(_translate("TeamWidget", "闫  旭", None))
        self.label_27.setText(_translate("TeamWidget", "界面组", None))
        self.label_28.setText(_translate("TeamWidget", "李文硕 林梓楠", None))
        self.label_29.setText(_translate("TeamWidget", "刘宸昊", None))
        self.websiteButton.setText(_translate("TeamWidget", "队式主页", None))
        self.ExitButton.setText(_translate("TeamWidget", "返回上级", None))
        self.label_2.setText(_translate("TeamWidget", "胡益铭", None))
        self.label_7.setText(_translate("TeamWidget", "李步宇", None))
        self.label_3.setText(_translate("TeamWidget", "朴镜潭", None))
        self.label_4.setText(_translate("TeamWidget", "刘帅祎", None))
        self.label_5.setText(_translate("TeamWidget", "宁雪妃", None))
        self.label_6.setText(_translate("TeamWidget", "李栋林", None))
        self.label_18.setText(_translate("TeamWidget", "吴  旦", None))
        self.label_8.setText(_translate("TeamWidget", "池雨泽", None))
        self.label_9.setText(_translate("TeamWidget", "陈浩贤", None))
        self.label_10.setText(_translate("TeamWidget", "谈至勋", None))
        self.label_11.setText(_translate("TeamWidget", "王  康", None))

