# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WebPlay.ui'
#
# Created: Sat Mar 14 00:55:48 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(769, 548)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.label.setStyleSheet(_fromUtf8("font: 75 16pt \"黑体\";\n"
"color: rgb(255, 0, 0);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.UserNameLabel = QtGui.QLabel(Form)
        self.UserNameLabel.setGeometry(QtCore.QRect(90, 10, 211, 41))
        self.UserNameLabel.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"font: 75 16pt \"黑体\";"))
        self.UserNameLabel.setText(_fromUtf8(""))
        self.UserNameLabel.setObjectName(_fromUtf8("UserNameLabel"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 54, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 54, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(160, 50, 591, 461))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.label_6 = QtGui.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.B1Button = QtGui.QPushButton(self.tab1)
        self.B1Button.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.B1Button.setObjectName(_fromUtf8("B1Button"))
        self.U1Button = QtGui.QPushButton(self.tab1)
        self.U1Button.setGeometry(QtCore.QRect(220, 20, 75, 23))
        self.U1Button.setObjectName(_fromUtf8("U1Button"))
        self.F1Button = QtGui.QPushButton(self.tab1)
        self.F1Button.setGeometry(QtCore.QRect(310, 20, 75, 23))
        self.F1Button.setObjectName(_fromUtf8("F1Button"))
        self.U2Button = QtGui.QPushButton(self.tab1)
        self.U2Button.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.U2Button.setObjectName(_fromUtf8("U2Button"))
        self.label_7 = QtGui.QLabel(self.tab1)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.B2Button = QtGui.QPushButton(self.tab1)
        self.B2Button.setGeometry(QtCore.QRect(130, 60, 75, 23))
        self.B2Button.setObjectName(_fromUtf8("B2Button"))
        self.F2Button = QtGui.QPushButton(self.tab1)
        self.F2Button.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.F2Button.setObjectName(_fromUtf8("F2Button"))
        self.U3Button = QtGui.QPushButton(self.tab1)
        self.U3Button.setGeometry(QtCore.QRect(220, 100, 75, 23))
        self.U3Button.setObjectName(_fromUtf8("U3Button"))
        self.label_8 = QtGui.QLabel(self.tab1)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 54, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.B3Button = QtGui.QPushButton(self.tab1)
        self.B3Button.setGeometry(QtCore.QRect(130, 100, 75, 23))
        self.B3Button.setObjectName(_fromUtf8("B3Button"))
        self.F3Button = QtGui.QPushButton(self.tab1)
        self.F3Button.setGeometry(QtCore.QRect(310, 100, 75, 23))
        self.F3Button.setObjectName(_fromUtf8("F3Button"))
        self.U4Button = QtGui.QPushButton(self.tab1)
        self.U4Button.setGeometry(QtCore.QRect(220, 140, 75, 23))
        self.U4Button.setObjectName(_fromUtf8("U4Button"))
        self.label_9 = QtGui.QLabel(self.tab1)
        self.label_9.setGeometry(QtCore.QRect(20, 140, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.B4Button = QtGui.QPushButton(self.tab1)
        self.B4Button.setGeometry(QtCore.QRect(130, 140, 75, 23))
        self.B4Button.setObjectName(_fromUtf8("B4Button"))
        self.F4Button = QtGui.QPushButton(self.tab1)
        self.F4Button.setGeometry(QtCore.QRect(310, 140, 75, 23))
        self.F4Button.setObjectName(_fromUtf8("F4Button"))
        self.U5Button = QtGui.QPushButton(self.tab1)
        self.U5Button.setGeometry(QtCore.QRect(220, 180, 75, 23))
        self.U5Button.setObjectName(_fromUtf8("U5Button"))
        self.label_10 = QtGui.QLabel(self.tab1)
        self.label_10.setGeometry(QtCore.QRect(20, 180, 54, 12))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.B5Button = QtGui.QPushButton(self.tab1)
        self.B5Button.setGeometry(QtCore.QRect(130, 180, 75, 23))
        self.B5Button.setObjectName(_fromUtf8("B5Button"))
        self.F5Button = QtGui.QPushButton(self.tab1)
        self.F5Button.setGeometry(QtCore.QRect(310, 180, 75, 23))
        self.F5Button.setObjectName(_fromUtf8("F5Button"))
        self.S1Label = QtGui.QLabel(self.tab1)
        self.S1Label.setGeometry(QtCore.QRect(70, 20, 54, 12))
        self.S1Label.setText(_fromUtf8(""))
        self.S1Label.setObjectName(_fromUtf8("S1Label"))
        self.S2Label = QtGui.QLabel(self.tab1)
        self.S2Label.setGeometry(QtCore.QRect(70, 60, 54, 12))
        self.S2Label.setText(_fromUtf8(""))
        self.S2Label.setObjectName(_fromUtf8("S2Label"))
        self.S3Label = QtGui.QLabel(self.tab1)
        self.S3Label.setGeometry(QtCore.QRect(70, 100, 54, 12))
        self.S3Label.setText(_fromUtf8(""))
        self.S3Label.setObjectName(_fromUtf8("S3Label"))
        self.S4Label = QtGui.QLabel(self.tab1)
        self.S4Label.setGeometry(QtCore.QRect(70, 140, 54, 12))
        self.S4Label.setText(_fromUtf8(""))
        self.S4Label.setObjectName(_fromUtf8("S4Label"))
        self.S5Label = QtGui.QLabel(self.tab1)
        self.S5Label.setGeometry(QtCore.QRect(70, 180, 54, 12))
        self.S5Label.setText(_fromUtf8(""))
        self.S5Label.setObjectName(_fromUtf8("S5Label"))
        self.RankingButton = QtGui.QPushButton(self.tab1)
        self.RankingButton.setGeometry(QtCore.QRect(20, 310, 75, 23))
        self.RankingButton.setObjectName(_fromUtf8("RankingButton"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.label_20 = QtGui.QLabel(self.tab2)
        self.label_20.setGeometry(QtCore.QRect(230, 10, 54, 12))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.MapCombo = QtGui.QComboBox(self.tab2)
        self.MapCombo.setGeometry(QtCore.QRect(290, 10, 161, 22))
        self.MapCombo.setObjectName(_fromUtf8("MapCombo"))
        self.label_21 = QtGui.QLabel(self.tab2)
        self.label_21.setGeometry(QtCore.QRect(230, 50, 54, 12))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.EnemyCombo = QtGui.QComboBox(self.tab2)
        self.EnemyCombo.setGeometry(QtCore.QRect(290, 50, 161, 22))
        self.EnemyCombo.setObjectName(_fromUtf8("EnemyCombo"))
        self.textBrowser = QtGui.QTextBrowser(self.tab2)
        self.textBrowser.setGeometry(QtCore.QRect(10, 80, 571, 341))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.FightButton = QtGui.QPushButton(self.tab2)
        self.FightButton.setGeometry(QtCore.QRect(490, 30, 75, 23))
        self.FightButton.setObjectName(_fromUtf8("FightButton"))
        self.UPAIButton = QtGui.QPushButton(self.tab2)
        self.UPAIButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.UPAIButton.setObjectName(_fromUtf8("UPAIButton"))
        self.CompileButton = QtGui.QPushButton(self.tab2)
        self.CompileButton.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.CompileButton.setObjectName(_fromUtf8("CompileButton"))
        self.label_22 = QtGui.QLabel(self.tab2)
        self.label_22.setGeometry(QtCore.QRect(100, 10, 81, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.AILabel = QtGui.QLabel(self.tab2)
        self.AILabel.setGeometry(QtCore.QRect(90, 40, 141, 16))
        self.AILabel.setText(_fromUtf8(""))
        self.AILabel.setObjectName(_fromUtf8("AILabel"))
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.IDLabel = QtGui.QLabel(Form)
        self.IDLabel.setGeometry(QtCore.QRect(70, 60, 54, 12))
        self.IDLabel.setText(_fromUtf8(""))
        self.IDLabel.setObjectName(_fromUtf8("IDLabel"))
        self.TeamLabel = QtGui.QLabel(Form)
        self.TeamLabel.setGeometry(QtCore.QRect(70, 90, 54, 12))
        self.TeamLabel.setText(_fromUtf8(""))
        self.TeamLabel.setObjectName(_fromUtf8("TeamLabel"))
        self.ScoreLabel = QtGui.QLabel(Form)
        self.ScoreLabel.setGeometry(QtCore.QRect(70, 120, 54, 12))
        self.ScoreLabel.setText(_fromUtf8(""))
        self.ScoreLabel.setObjectName(_fromUtf8("ScoreLabel"))
        self.ReturnButton = QtGui.QPushButton(Form)
        self.ReturnButton.setGeometry(QtCore.QRect(10, 510, 75, 23))
        self.ReturnButton.setObjectName(_fromUtf8("ReturnButton"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "欢迎您，", None))
        self.label_3.setText(_translate("Form", "您的队伍：", None))
        self.label_4.setText(_translate("Form", "您的ID：", None))
        self.label_5.setText(_translate("Form", "您的积分：", None))
        self.label_6.setText(_translate("Form", "第一关：", None))
        self.B1Button.setText(_translate("Form", "关卡介绍", None))
        self.U1Button.setText(_translate("Form", "上传AI", None))
        self.F1Button.setText(_translate("Form", "战斗！", None))
        self.U2Button.setText(_translate("Form", "上传AI", None))
        self.label_7.setText(_translate("Form", "第二关：", None))
        self.B2Button.setText(_translate("Form", "关卡介绍", None))
        self.F2Button.setText(_translate("Form", "战斗！", None))
        self.U3Button.setText(_translate("Form", "上传AI", None))
        self.label_8.setText(_translate("Form", "第三关：", None))
        self.B3Button.setText(_translate("Form", "关卡介绍", None))
        self.F3Button.setText(_translate("Form", "战斗！", None))
        self.U4Button.setText(_translate("Form", "上传AI", None))
        self.label_9.setText(_translate("Form", "第四关：", None))
        self.B4Button.setText(_translate("Form", "关卡介绍", None))
        self.F4Button.setText(_translate("Form", "战斗！", None))
        self.U5Button.setText(_translate("Form", "上传AI", None))
        self.label_10.setText(_translate("Form", "第五关：", None))
        self.B5Button.setText(_translate("Form", "关卡介绍", None))
        self.F5Button.setText(_translate("Form", "战斗！", None))
        self.RankingButton.setText(_translate("Form", "查看排行榜", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Form", "测试赛", None))
        self.label_20.setText(_translate("Form", "选择地图：", None))
        self.label_21.setText(_translate("Form", "选择对手：", None))
        self.FightButton.setText(_translate("Form", "战斗！", None))
        self.UPAIButton.setText(_translate("Form", "上传AI", None))
        self.CompileButton.setText(_translate("Form", "编译", None))
        self.label_22.setText(_translate("Form", "您现在的AI：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "排位赛", None))
        self.ReturnButton.setText(_translate("Form", "返回", None))

